apiVersion: v1
kind: Service
metadata:
  name: xgen-agent
  namespace: xgen-system
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - name: http
      port: {{ .Values.agent.service.port }}
      targetPort: http
      {{- if eq .Values.agent.service.type "NodePort" }}
      nodePort: {{ .Values.agent.service.nodePort }}
      {{- end }}
  selector:
    app: xgen-agent
