apiVersion: v1
kind: Service
metadata:
  name: xgen-agent
  namespace: xgen-system
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - name: http
      port: {{ .Values.agent.service.port }}
      targetPort: http
  selector:
    app: xgen-agent
