apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-quota
  namespace: {{ .Values.sandbox.namespace }}
spec:
  hard:
    pods: {{ .Values.sandbox.resourceQuota.pods | quote }}
    requests.cpu: {{ .Values.sandbox.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.sandbox.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.sandbox.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.sandbox.resourceQuota.limitsMemory | quote }}
